import assert from 'node:assert/strict';
import { URL } from 'node:url';
import console from 'node:console';
import { readFile } from 'node:fs/promises';
import { runInNewContext } from 'node:vm';
import ts from 'typescript';
import { drawingFrom, drawingPolygon } from './perimeter.ts';

const source = await readFile(new URL('../pages/dashboard/components/CaseEvidence.tsx', import.meta.url), 'utf8');
const ast = ts.createSourceFile('CaseEvidence.tsx', source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
let handler, startHandler;
function visit(node) { if (ts.isFunctionDeclaration(node) && node.name?.text === 'selectStatus') handler = node.getText(ast); if (ts.isFunctionDeclaration(node) && node.name?.text === 'startDrawing') startHandler = node.getText(ast); ts.forEachChild(node, visit); }
visit(ast);
let draft = null, status = 'OPEN', writes = 0;
const context = { mutation: { reset() {} }, detail: { id: 'case', version: 3, verification: 'UNVERIFIED' }, description: 'Inspection confirmed visible fire.', fieldId: 'actual-field', drawingFrom, confirmation: false, setDraft: value => { draft = value; }, setStatus: value => { status = value; }, setDescription() {}, window: { confirm: () => true }, verifyGovernmentCase: () => { writes++; } };
const select = runInNewContext(ts.transpileModule(handler + '\nselectStatus;', { compilerOptions: { target: ts.ScriptTarget.ES2022 } }).outputText, context);
select('CONFIRMED_FIRE');
assert.equal(draft, null);
assert.equal(status, 'CONFIRMED_FIRE');
Object.assign(context, { authorized: true, canDraw: true, pending: false, draft: null, reportReviewStatus: 'UNDER_REVIEW' });
const start = runInNewContext(ts.transpileModule(startHandler + '\nstartDrawing;', { compilerOptions: { target: ts.ScriptTarget.ES2022 } }).outputText, context);
start();
assert.equal(draft.caseId, 'case');
assert.equal(draft.confirmation.fieldUpdateId, 'actual-field');
assert.equal(draft.version, 3);
assert.equal(writes, 0);
assert.throws(() => drawingPolygon(draft.drawing), /Close each ring/);
context.confirmation = true;
context.window.confirm = () => false;
select('MONITORING');
assert.ok(draft);
context.window.confirm = () => true;
select('MONITORING');
assert.equal(draft, null);
assert.equal(status, 'MONITORING');
assert.equal(writes, 0);
assert.match(source, /detail.verification !== "CONFIRMED_FIRE"/);
assert.match(source, /detail.activeAssignmentCount > 0/);
assert.doesNotMatch(source, /operatorAuthorityConfigured|configured mandate/);
assert.match(source, /authorityReference: authority.trim\(\)/);
const perimeter = await readFile(new URL('../pages/dashboard/components/CasePerimeter.tsx', import.meta.url), 'utf8');
assert.match(perimeter, /if \(input.confirmation\)/);
assert.match(perimeter, /operatorWorkflow: true, outcome: "CONFIRMED_FIRE"/);
assert.match(perimeter, /else await savePerimeter/);
assert.match(perimeter, /input.version !== detail.version/);
console.log('Status selection opens an unverified draft without writes; open rings, cancellation and transition gates passed.');
