import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { URL } from "node:url";
import { workspacePath, safeWorkspaceDestination } from "./dashboard.ts";

assert.equal(workspacePath("ADMIN"), "/dashboard");
assert.equal(workspacePath("USER"), "/dashboard");
assert.equal(safeWorkspaceDestination("/monitoring", "ADMIN"), "/monitoring");
assert.equal(safeWorkspaceDestination("/monitoring", "USER"), "/dashboard");
for (const path of ["/report", "/my-reports", "/my-reports/one", "/dashboard?panel=report", "/monitoring?panel=my-reports"]) assert.equal(safeWorkspaceDestination(path, "ADMIN"), "/dashboard");
const source = path => readFile(new URL(path, import.meta.url), "utf8");
const dashboard = await source("../pages/dashboard/DashboardPage.tsx");
assert.match(dashboard, /panel === "cases" && !selected \? <GovernmentWorklist/);
assert.doesNotMatch(dashboard, /perimeterDraft \? <GovernmentWorklist/);
assert.match(dashboard, /user.role === "USER" && pathname === home && <ReportPage/);
assert.match(dashboard, /aria-label="Feed visibility"/);
assert.match(dashboard, /<DraftGuard dirty=\{!!perimeterDraft\} pending=\{!!perimeterDraft\?\.pending\}/);
assert.match(dashboard, /import \{ ItemDetail \} from "\.\/components\/CitizenDashboard"/);
const worklist = await source("../pages/dashboard/components/GovernmentWorklist.tsx");
assert.match(worklist, /draft\?\.caseId \?\? params.get\("case"\)/);
assert.match(worklist, /Open case on map/);
assert.match(worklist, /fieldset disabled=\{!!draft\}><CaseEvidence/);
const evidence = await source("../pages/dashboard/components/CaseEvidence.tsx");
assert.match(evidence, /if \(!compatible \|\| !field \|\| !confirmed/);
const reports = await source("../pages/dashboard/components/GovernmentReports.tsx");
assert.match(reports, /fieldset disabled=\{reports.failed \|\| reports.loading\}/);
const account = await source("../components/auth/AccountMenu.tsx");
assert.match(account, /hover:bg-secondary focus-visible:bg-secondary/);
assert.match(account, /to="\/profile"/);
