import { URL } from "node:url";
import { runInNewContext } from "node:vm";
import ts from "typescript";
import { QueryClient, InfiniteQueryObserver } from "@tanstack/react-query";
import { setTimeout } from "node:timers/promises";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { feedPageSize, nextFeedPage, uniqueFeedItems, publicationPath, publicationHasMap } from "./publications.ts";
import { reportStatus, reportStatusLabel } from "./report-status.ts";
assert.equal(feedPageSize, 10);
const page = (number, ids, total = 21) => ({ data: ids.map(id => ({ id })), meta: { page: number, pageSize: 10, total } });
assert.equal(nextFeedPage(page(1, ['a'])), 2);
assert.equal(nextFeedPage(page(3, ['z'])), undefined);
assert.equal(nextFeedPage(page(2, [])), undefined);
assert.deepEqual(uniqueFeedItems([page(1, ['a', 'b']), page(2, ['b', 'c'])]).map(item => item.id), ['a', 'b', 'c']);
assert.equal(publicationPath('approved-update', 'news'), '/publications/approved-update?from=news');
assert.equal(publicationHasMap({ status: 'PUBLISHED', latitude: null, longitude: null }), false);
assert.equal(publicationHasMap({ status: 'PUBLISHED', latitude: 0, longitude: 0 }), true);
assert.equal(publicationHasMap({ status: 'PUBLISHED', outcome: 'DECLINED', latitude: 0, longitude: 0 }), false);
const hook = await readFile(new URL('../hooks/dashboard/usePublications.ts', import.meta.url), 'utf8');
assert.match(hook, /queryKey: \["dashboard", user.id, user.role, "publications", news, from\]/);
assert.match(hook, /signal.throwIfAborted/);
assert.match(hook, /cancelRefetch: false/);
assert.match(hook, /forbidden \? \[\]/);
assert.match(hook, /clearDashboardQueries/);
const row = await readFile(new URL('../pages/dashboard/components/FeedRow.tsx', import.meta.url), 'utf8');
assert.match(row, /new IntersectionObserver/);
assert.match(row, /observer.disconnect/);
assert.match(row, /View details/);
const government = await readFile(new URL('../pages/dashboard/DashboardPage.tsx', import.meta.url), 'utf8');
assert.match(government, /feed \? 10 : 20/);
assert.match(government, /onOpen=\{\(\) => viewReport\(item\)\}/);
assert.doesNotMatch(government, /onMap=/);
const detail = await readFile(new URL('../pages/dashboard/components/PublicationPage.tsx', import.meta.url), 'utf8');
assert.match(detail, /public\/information/);
assert.match(detail, /public\/media/);
assert.doesNotMatch(detail, /downloadPhoto|admin\/reports|reporterId/);
let options, observer, failure = null, release = null;
const requests = [];
const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
class AuthError extends Error {}
const compiled = ts.transpileModule(hook.slice(hook.indexOf('export function usePublications')).replace('export function', 'function') + '\nusePublications;', { compilerOptions: { target: ts.ScriptTarget.ES2022 } }).outputText;
const useFeed = runInNewContext(compiled, {
  useInfiniteQuery: value => { options = value; return observer?.getCurrentResult() ?? {}; },
  AuthError, isAxiosError: () => false, feedPageSize, nextFeedPage, uniqueFeedItems,
  publicRequest: async (user, path, signal, params) => {
    requests.push({ user, path, signal, params });
    if (release) await new Promise(resolve => { release = resolve; });
    signal.throwIfAborted();
    if (failure) throw failure;
    return page(params.page, params.page === 1 ? ['a', 'b'] : ['b', 'c']);
  },
});
const user = { id: 'a', role: 'USER' };
useFeed(user, true);
observer = new InfiniteQueryObserver(client, options);
let unsubscribe = observer.subscribe(() => {});
await observer.refetch();
assert.equal(requests[0].params.pageSize, 10);
release = true;
useFeed(user, true).loadMore();
useFeed(user, true).loadMore();
await setTimeout(0);
assert.equal(requests.filter(request => request.params.page === 2).length, 1);
const finish = release; release = null; finish();
await observer.fetchNextPage({ cancelRefetch: false });
assert.deepEqual(useFeed(user, true).items.map(item => item.id), ['a', 'b', 'c']);
failure = new Error('offline');
await observer.fetchNextPage();
assert.equal(useFeed(user, true).items.length, 3);
failure = new AuthError('account changed');
await observer.refetch();
assert.equal(useFeed(user, true).items.length, 0);
failure = null;
unsubscribe();
useFeed({ id: 'b', role: 'USER' }, false, 'new-range');
observer.setOptions(options);
assert.equal(useFeed({ id: 'b', role: 'USER' }, false, 'new-range').items.length, 0);
unsubscribe = observer.subscribe(() => {});
await observer.refetch();
assert.equal(requests.at(-1).params.page, 1);
release = true;
void observer.fetchNextPage();
await setTimeout(0);
const pending = requests.at(-1);
unsubscribe();
assert.equal(pending.signal.aborted, true);
const abortFinish = release; release = null; abortFinish();
client.clear();
let observed, disconnected = false, loadCount = 0, callback, effect;
const sentinelSource = row.slice(row.indexOf('export function FeedSentinel'));
const sentinel = ts.transpileModule(sentinelSource.replace('export function', 'function') + '\nFeedSentinel;', { compilerOptions: { target: ts.ScriptTarget.ES2022, jsx: ts.JsxEmit.React } }).outputText;
const root = {};
const node = { closest: () => root };
const renderSentinel = runInNewContext(sentinel, {
  useRef: () => ({ current: node }), useEffect: fn => { effect = fn; }, React: { createElement: () => null },
  IntersectionObserver: class { constructor(fn, config) { callback = fn; assert.equal(config.root, root); } observe(value) { observed = value; } disconnect() { disconnected = true; } },
});
renderSentinel({ enabled: true, onLoad: () => loadCount++ });
const cleanup = effect();
assert.equal(observed, node);
callback([{ isIntersecting: false }]); assert.equal(loadCount, 0);
callback([{ isIntersecting: true }]); assert.equal(loadCount, 1);
cleanup(); assert.equal(disconnected, true);
observed = null;
renderSentinel({ enabled: false, onLoad: () => loadCount++ }); effect();
assert.equal(observed, null);
const base = { reviewStatus: "REVIEWED", case: { verificationStatus: "NOT_FIRE", handlingStatus: "CLOSED" } };
assert.equal(reportStatus(base), "REVIEWED");
assert.equal(reportStatus({ ...base, reviewStatus: "DECLINED" }), "DECLINED");
assert.equal(reportStatus({ ...base, reviewStatus: "NEW", case: null }), null);
assert.equal(reportStatusLabel({ ...base, reviewStatus: "UNDER_REVIEW" }), "In progress");
assert.equal(reportStatus({ ...base, case: { verificationStatus: "CONFIRMED_FIRE" } }), "CONFIRMED");
const news = await readFile(new URL("../pages/dashboard/components/NewsFeed.tsx", import.meta.url), "utf8");
assert.match(news, /usePublications/);
assert.match(news, /FeedSentinel/);
assert.doesNotMatch(news, /setSelected|Show more|>Previous<|>Next</);
const routes = await readFile(new URL("../config/routes.ts", import.meta.url), "utf8");
assert.match(routes, /publications\/:slug/);
assert.match(news, /useCitizenFeed/);
assert.match(news, /item.kind === "PUBLICATION"/);
assert.match(news, /FeedRow/);
assert.match(news, /FeedEmpty/);
assert.match(news, /FeedRowsSkeleton/);
assert.doesNotMatch(news, /admin\/reports|downloadPhoto|reporterId/);
assert.doesNotMatch(await readFile(new URL("../pages/dashboard/DashboardPage.tsx", import.meta.url), "utf8"), /<NewsFeed/);
assert.match(await readFile(new URL("../pages/dashboard/components/CitizenDashboard.tsx", import.meta.url), "utf8"), /<NewsFeed/);
