import assert from 'node:assert/strict';
import { parseWindContext, windArrow } from './wind.ts';
const now = Date.parse('2026-09-17T10:00:00Z');
const value = { status: 'READY', evaluatedAt: '2026-09-17T10:00:00.000Z', usableUntil: '2026-09-17T12:00:00.000Z', forecast: { id: 'forecast', provider: 'BMKG', regionId: 'region', regionName: 'Village', issuedAt: '2026-09-17T06:00:00.000Z', validAt: '2026-09-17T09:00:00.000Z', fetchedAt: '2026-09-17T08:00:00.000Z' }, windSpeedKmh: 12, windFromDegrees: 0, windToDegrees: 180, summary: 'Wind from N toward S.', disclaimer: 'Downwind attention, not predicted perimeter', spatialExtent: null, settlementExposure: 'UNAVAILABLE', ruleVersion: 'wind-context-1' };
const context = parseWindContext(value);
const detail = { id: 'case', title: 'Selected case', verification: 'CONFIRMED_FIRE', latitude: -1, longitude: 110, windContext: context };
assert.equal(windArrow(detail, now)?.degrees, 180);
assert.equal(windArrow(detail, Date.parse(value.usableUntil)), null);
assert.equal(windArrow(detail, now - 1), null);
assert.equal(windArrow({ ...detail, verification: 'UNVERIFIED' }, now), null);
assert.equal(windArrow({ ...detail, latitude: null }, now), null);
assert.equal(windArrow({ ...detail, windContext: { ...context, status: 'STALE' } }, now), null);
assert.equal(parseWindContext(undefined), null);
for (const patch of [{ windSpeedKmh: -1 }, { windFromDegrees: 360 }, { windToDegrees: 90 }, { windSpeedKmh: null }, { forecast: null }, { usableUntil: null }, { status: 'BOGUS' }, { spatialExtent: { radius: 10 } }, { settlementExposure: 'SAFE' }, { evaluatedAt: 'bad' }]) assert.throws(() => parseWindContext({ ...value, ...patch }));
assert.equal(parseWindContext({ ...value, status: 'CALM', windSpeedKmh: 0, windFromDegrees: null, windToDegrees: null }).status, 'CALM');
assert.equal(parseWindContext({ ...value, status: 'NO_VERIFIED_REGION', forecast: null, usableUntil: null, windSpeedKmh: null, windFromDegrees: null, windToDegrees: null }).forecast, null);
