import { lazy, Suspense, useCallback, useEffect, useMemo, useRef, useState, type PointerEvent, type KeyboardEvent, type MouseEvent } from "react";
import ReportPage from "@/pages/report";
import ReportsPage from "@/pages/reports";
import { boundPanel, workspacePath } from "@/lib/dashboard";
import { Link, useLoaderData, useLocation, useSearchParams } from "react-router-dom";
import { Dialog, Popover, Select } from "radix-ui";
import { ArrowLeft, ArrowUpRight, Check, ClipboardList, Crosshair, Flame, List, MapPin, RefreshCw, Search, ShieldCheck, Satellite, SlidersHorizontal, X } from "lucide-react";
import { dashboardLogin } from "@/lib";
import { rainforestSmall } from "@/assets";
import { WorkspaceNav } from "@/components/common";

import type { DashboardUser, MapItem, ReportDraft } from "@/types";
import { handlingLabels, verificationLabels } from "@/constants";
import { Button } from "@/components/ui";
import { CitizenDashboard, GovernmentWorklist, LayerPreview } from "@/pages/dashboard/components";
import { useDashboardSession, useQueryGetMap } from "@/hooks/dashboard";
import { ageMap, filterMap, hasPoint, formatTime, mapAvailability } from "@/pages/dashboard/utils";

const SituationMap = lazy(() => import("@/pages/dashboard/components/SituationMap"));
const control = "min-h-11 w-full rounded-xl border border-input bg-white px-3 text-sm";

export function Component() {
  const user = useLoaderData() as DashboardUser;
  const { signingOut } = useDashboardSession(user);
  if (signingOut) return <main className="grid h-dvh place-items-center bg-background"><p role="status">Checking your session…</p></main>;
  return user.role === "USER" ? <CitizenDashboard key={`${user.id}:${user.role}`} user={user} /> : <Workspace key={`${user.id}:${user.role}`} user={user} />;
}

function Workspace({ user }: { user: DashboardUser }) {
  const { pathname } = useLocation();
  const home = workspacePath(user.role);
  const [params, setParams] = useSearchParams();
  const feed = pathname === "/feed" || params.get("view") === "feed";
  const [reportPending, setReportPending] = useState(false);
  const [pick, setPick] = useState<{ latitude: string; longitude: string; locationMode: ReportDraft["locationMode"]; receive: (latitude: string, longitude: string) => void } | null>(null);
  const reportOpen = params.get("panel") === "report";
  const myReports = params.get("panel") === "my-reports";
  const [detailDraft, setDetailDraft] = useState({ dirty: false, pending: false });
  const handleDetailDraft = useCallback((dirty: boolean, pending: boolean) => setDetailDraft({ dirty, pending }), []);
  const reportOpener = useRef<HTMLElement | null>(null);
  const worklistOpener = useRef<HTMLElement | null>(null);
  function restoreFocus(opener: HTMLElement | null, selector: string) {
    const visible = (element: HTMLElement) => element.isConnected && element.getClientRects().length > 0 && !element.closest('[inert], [aria-hidden="true"]');
    const target = opener && visible(opener) ? opener : Array.from(document.querySelectorAll<HTMLElement>(selector)).find(visible);
    target?.focus();
  }
  function openWorklist(opener?: HTMLElement) { if (!mobileOpen) worklistOpener.current = opener ?? (document.activeElement instanceof HTMLElement ? document.activeElement : null); setMobileOpen(true); }
  function openReport(event?: MouseEvent<HTMLButtonElement>) { if (reportPending) return; if (event) reportOpener.current = event.currentTarget; setParams(current => { current.set("panel", "report"); current.delete("view"); return current; }, { replace: true }); }
  function closeReport() { if (reportPending) return; setParams(current => { current.delete("panel"); return current; }, { replace: true }); }
  const [box, setBox] = useState(() => boundPanel({ x: 24, y: 96, width: 380, height: window.innerHeight - 120 }, { width: window.innerWidth, height: window.innerHeight }));
  const [sheetHeight, setSheetHeight] = useState(68);
  const [reportsHeight, setReportsHeight] = useState(72);
  const [reportBox, setReportBox] = useState(() => boundPanel({ x: window.innerWidth - 424, y: 96, width: 400, height: window.innerHeight - 120 }, { width: window.innerWidth, height: window.innerHeight }));
  const gesture = useRef<{ x: number; y: number; box: typeof box; height: number; mode: "move" | "resize" | "sheet" | "reports"; report: boolean } | null>(null);
  function adjust(next: typeof box, report = false) { (report ? setReportBox : setBox)(boundPanel(next, { width: window.innerWidth, height: window.innerHeight })); }
  useEffect(() => { const resize = () => { const viewport = { width: window.innerWidth, height: window.innerHeight }; setBox(current => boundPanel(current, viewport)); setReportBox(current => boundPanel(current, viewport)); }; window.addEventListener("resize", resize); return () => window.removeEventListener("resize", resize); }, []);
  function start(event: PointerEvent<HTMLButtonElement>, mode: "move" | "resize" | "sheet" | "reports", report = false) { if (event.button !== 0 || !event.isPrimary) return; event.currentTarget.setPointerCapture(event.pointerId); gesture.current = { x: event.clientX, y: event.clientY, box: report ? reportBox : box, height: mode === "reports" ? reportsHeight : sheetHeight, mode, report }; }
  function move(event: PointerEvent<HTMLButtonElement>) { const initial = gesture.current; if (!initial || !event.currentTarget.hasPointerCapture(event.pointerId)) return; const x = event.clientX - initial.x, y = event.clientY - initial.y; if (initial.mode === "reports") setReportsHeight(Math.max(44, Math.min(82, initial.height - y / window.innerHeight * 100))); else if (initial.mode === "sheet") setSheetHeight(Math.max(34, Math.min(86, initial.height - y / window.innerHeight * 100))); else adjust(initial.mode === "move" ? { ...initial.box, x: initial.box.x + x, y: initial.box.y + y } : { ...initial.box, width: initial.box.width + x, height: initial.box.height + y }, initial.report); }
  function keyboard(event: KeyboardEvent<HTMLButtonElement>, resize = false, report = false) { const current = report ? reportBox : box; const x = event.key === "ArrowRight" ? 20 : event.key === "ArrowLeft" ? -20 : 0; const y = event.key === "ArrowDown" ? 20 : event.key === "ArrowUp" ? -20 : 0; if (!x && !y) return; event.preventDefault(); adjust(resize ? { ...current, width: current.width + x, height: current.height + y } : { ...current, x: current.x + x, y: current.y + y }, report); }
  const pointerEnd = () => { gesture.current = null; };
  const [hours, setHours] = useState(48);
  const [search, setSearch] = useState("");
  const [publications, setPublications] = useState(true);
  const [hotspots, setHotspots] = useState(true);
  const [panel, setPanel] = useState<"reports" | "results" | "cases">(user.role === "ADMIN" ? "cases" : "reports");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [desktop, setDesktop] = useState(() => window.matchMedia("(min-width: 768px)").matches);
  useEffect(() => {
    const media = window.matchMedia("(min-width: 768px)");
    const update = () => setDesktop(media.matches);
    media.addEventListener("change", update);
    return () => media.removeEventListener("change", update);
  }, []);
  const [limit, setLimit] = useState(40);
  const loaded = useQueryGetMap(user, hours);
  const data = useMemo(() => loaded.data ? ageMap(loaded.data, loaded.now) : null, [loaded.data, loaded.now]);
  const items = useMemo(() => filterMap(data?.items ?? [], search, feed || publications, !feed && hotspots), [data, search, feed, publications, hotspots]);
  const selected = items.find(item => item.id === params.get("observation")) ?? null;
  const availability = mapAvailability(data, loaded.failed);
  function select(id: string, opener?: HTMLElement) { if (reportPending || pick) return; setParams(current => { current.set("observation", id); return current; }, { replace: true }); openWorklist(opener); }
  function clearSelection() { if (reportPending) return; setParams(current => { current.delete("observation"); return current; }, { replace: true }); }
  const searchControl = (id: string) => <div className="relative min-w-0 flex-1"><Search size={17} className="pointer-events-none absolute left-3.5 top-3.5 text-primary" aria-hidden="true" /><label htmlFor={id} className="sr-only">Search {feed ? "published summaries" : "observations"}</label><input id={id} type="search" maxLength={200} className="min-h-11 w-full rounded-full border border-primary/15 bg-secondary/40 pl-10 pr-3 text-sm outline-offset-2" placeholder={feed ? "Search published updates" : "Search observations or region"} value={search} onChange={event => { setSearch(event.target.value); setLimit(40); }} /></div>;
  const filters = <Popover.Root><Popover.Trigger asChild><Button variant="ghost" className="rounded-full" aria-label="Observation filters"><SlidersHorizontal size={17} aria-hidden="true" /><span className="hidden md:inline">Filters</span></Button></Popover.Trigger><Popover.Portal><Popover.Content side="top" sideOffset={12} collisionPadding={16} className="z-50 w-72 rounded-2xl border bg-white p-5 text-forest shadow-xl"><div className="mb-4 flex items-center justify-between"><h2 className="font-extrabold">Filters</h2><Popover.Close asChild><Button size="icon" variant="ghost" aria-label="Close filters"><X size={17} /></Button></Popover.Close></div><label htmlFor="map-window" className="text-sm font-bold">Time range<Select.Root value={String(hours)} onValueChange={value => { setHours(Number(value)); setLimit(40); }}><Select.Trigger id="map-window" className={`${control} mt-2 flex items-center justify-between border-emerald-800/30 text-forest focus-visible:outline-2 focus-visible:outline-emerald-700`}><Select.Value /><Select.Icon aria-hidden="true">⌄</Select.Icon></Select.Trigger><Select.Portal><Select.Content position="popper" sideOffset={6} collisionPadding={12} className="z-80 max-h-[var(--radix-select-content-available-height)] w-[var(--radix-select-trigger-width)] overflow-y-auto rounded-xl border border-emerald-800/20 bg-white p-1 text-forest shadow-xl"><Select.Viewport>{[[24, "Last 24 hours"], [48, "Last 48 hours"], [168, "Last 7 days"]].map(([value, label]) => <Select.Item key={value} value={String(value)} className="flex min-h-11 cursor-pointer items-center justify-between rounded-lg px-3 text-sm outline-none data-[highlighted]:bg-emerald-50 data-[state=checked]:bg-emerald-800 data-[state=checked]:text-white"><Select.ItemText>{label}</Select.ItemText><Select.ItemIndicator aria-hidden="true">✓</Select.ItemIndicator></Select.Item>)}</Select.Viewport></Select.Content></Select.Portal></Select.Root></label>
    {!feed && <fieldset className="mt-5"><legend className="mb-3 text-sm font-bold">Map layers</legend><div className="grid grid-cols-2 gap-3">{([{ label: "Published summaries", checked: publications, change: setPublications, hotspot: false }, { label: "Satellite hotspots", checked: hotspots, change: setHotspots, hotspot: true }]).map(layer => <label key={layer.label} className={`cursor-pointer rounded-sm border p-1.5 focus-within:outline-2 focus-within:outline-primary ${layer.checked ? "border-primary bg-linear-to-b from-white to-emerald-50" : "border-primary/15 bg-white"}`}><LayerPreview hotspot={layer.hotspot} /><span className="flex min-h-11 items-center gap-2 px-1 py-2 text-xs font-bold"><input type="checkbox" className="size-4 shrink-0 accent-primary" checked={layer.checked} onChange={event => layer.change(event.target.checked)} />{layer.label}</span></label>)}</div></fieldset>}</Popover.Content></Popover.Portal></Popover.Root>;
  const actions = <>{filters}<Button variant="ghost" className="rounded-full" data-worklist-trigger aria-label="Open observation list" onClick={event => { setPanel("results"); clearSelection(); openWorklist(event.currentTarget); }}><List size={18} aria-hidden="true" /><span>List</span></Button>{user.role === "ADMIN" ? <Button variant="ghost" className="rounded-full" data-worklist-trigger onClick={event => { setPanel("cases"); clearSelection(); openWorklist(event.currentTarget); }}><ShieldCheck size={17} aria-hidden="true" /><span>Cases</span></Button> : null}<Button asChild variant="ghost" className="rounded-full"><Link to={`${home}?panel=my-reports`}><ClipboardList size={17} aria-hidden="true" /><span className="hidden md:inline">My reports</span><span className="sr-only md:hidden">My reports</span></Link></Button>{pathname === "/feed" ? <Button asChild className="rounded-full"><Link to={`${home}?panel=report`}>Report</Link></Button> : <Button data-report-trigger className="rounded-full" disabled={reportPending} onClick={openReport}>Report</Button>}</>;
  const observations = <>
    <div className="p-4">{availability && <p role={loaded.failed ? "alert" : "status"} className="mb-4 hidden rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-950 md:block">{availability}</p>}
      <ul className="space-y-2">{items.slice(0, limit).map(item => <li key={item.id}><button type="button" className="group flex w-full gap-3 rounded-xl border border-primary/10 bg-white p-4 text-left transition-colors hover:border-primary/40 hover:bg-secondary/30" onClick={event => select(item.id, event.currentTarget)}><ItemIcon item={item} /><span className="min-w-0 flex-1"><span className="block text-sm font-extrabold leading-5">{item.title}</span><span className="mt-1 block text-xs text-muted-foreground">{item.verification ? verificationLabels[item.verification] : "Satellite hotspot"}</span><span className="mt-2 block text-xs text-muted-foreground">{formatTime(item.time)}</span>{!hasPoint(item) && <span className="mt-1 block text-xs">No public map point</span>}</span><ArrowUpRight size={15} aria-hidden="true" className="shrink-0 text-primary" /></button></li>)}</ul>
      {data && !items.length && <div className="py-10 text-center"><h3 className="font-extrabold">No matching observations</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">No published updates match your filters.</p></div>}
      {items.length > limit && <Button variant="outline" className="mt-4 w-full rounded-full" onClick={() => setLimit(value => value + 40)}>Show more</Button>}
      {data?.limited && <p className="mt-4 text-xs">Results are limited. Narrow the time range.</p>}
    </div>
    <div className="mt-auto border-t border-primary/10 p-4 text-xs leading-5 text-muted-foreground">{data?.lastSuccessAt && <p>Satellite source refreshed {formatTime(data.lastSuccessAt)}.</p>}</div>
  </>;
  const panelContent = selected ? <><Button variant="ghost" className="m-3 w-fit" onClick={clearSelection}><ArrowLeft size={16} aria-hidden="true" />Back to list</Button><ItemDetail item={selected} />{feed && hasPoint(selected) && <Button asChild className="mx-5 mb-5 rounded-full"><Link to={`${home}?observation=${encodeURIComponent(selected.id)}`}>View approved point on map</Link></Button>}</> : panel === "cases" ? <GovernmentWorklist user={user} /> : panel === "reports" ? <><header className="border-b px-7 py-6"><h2 className="text-2xl font-extrabold">My reports</h2></header><ReportsPage user={user} id={params.get("report")} onDraft={handleDetailDraft} /></> : observations;
  return <main className="relative isolate h-dvh overflow-hidden bg-secondary/40 text-forest">
    <h1 className="sr-only">{feed ? "Published updates" : user.role === "ADMIN" ? "Coordination map" : "My reports"}</h1>
    <div inert={reportPending}><WorkspaceNav user={user}><div className="space-y-2">{searchControl("mobile-observation-search")}<div className="flex items-center justify-between gap-1">{actions}</div></div></WorkspaceNav></div>
    {!feed && <section aria-label="Situation map" className="absolute inset-0"><Suspense fallback={<p role="status" className="px-6 pt-56 sm:pt-28">Loading map…</p>}><SituationMap items={items} selected={selected} pick={pick} onSelect={select} onPick={pick ? (latitude, longitude) => setPick(current => current ? { ...current, latitude, longitude } : null) : undefined} /></Suspense></section>}
    {!feed && desktop && !myReports && <aside aria-label="Map worklist" style={{ left: box.x, top: box.y, width: box.width, height: box.height }} className="absolute z-20 hidden flex-col overflow-hidden rounded-sm border border-primary/10 bg-white shadow-xl md:flex"><button type="button" aria-label="Move panel using arrow keys or drag" className="min-h-11 shrink-0 touch-none cursor-move border-b bg-secondary/40 px-4 text-left text-xs font-bold focus-visible:outline-2 focus-visible:outline-primary" onPointerDown={event => start(event, "move")} onPointerMove={move} onPointerUp={pointerEnd} onPointerCancel={pointerEnd} onLostPointerCapture={pointerEnd} onKeyDown={event => keyboard(event)}><span aria-hidden="true" className="mx-auto block h-1.5 w-12 rounded-full bg-primary/25" /><span className="sr-only">Move panel</span></button>{user.role === "ADMIN" && <div className="flex shrink-0 gap-1 border-b bg-secondary/30 p-2">{([['results', 'Public observations'], ['cases', 'Internal cases']] as const).map(([value, label]) => <button key={value} type="button" aria-pressed={panel === value && !selected} onClick={() => { setPanel(value); clearSelection(); }} className={`min-h-11 flex-1 rounded-xl text-xs font-extrabold ${panel === value && !selected ? "bg-primary text-white" : "hover:bg-white"}`}>{label}</button>)}</div>}<div className="flex min-h-0 flex-1 flex-col overflow-y-auto overscroll-contain">{panelContent}</div><button type="button" aria-label="Resize panel using arrow keys or drag" className="min-h-11 shrink-0 touch-none cursor-nwse-resize border-t px-4 text-right text-xs font-bold focus-visible:outline-2 focus-visible:outline-primary" onPointerDown={event => start(event, "resize")} onPointerMove={move} onPointerUp={pointerEnd} onPointerCancel={pointerEnd} onLostPointerCapture={pointerEnd} onKeyDown={event => keyboard(event, true)}><span aria-hidden="true" className="mx-auto block h-1.5 w-12 rounded-full bg-primary/25" /><span className="sr-only">Resize panel</span></button></aside>}
    {feed && <section aria-label="Published update feed" className="absolute inset-0 overflow-y-auto overscroll-contain bg-white px-4 pb-32 pt-56 sm:px-6 sm:pt-28"><div className="mx-auto max-w-2xl">
      <header className="relative mb-5 flex min-h-40 items-end justify-between gap-4 overflow-hidden rounded-2xl bg-forest p-5 text-white shadow-sm"><img src={rainforestSmall} alt="" aria-hidden="true" className="absolute inset-0 size-full object-cover opacity-65" decoding="async" /><div aria-hidden="true" className="absolute inset-0 bg-linear-to-r from-forest via-forest/80 to-emerald-900/25" /><div className="relative"><h2 className="text-2xl font-extrabold tracking-tight">Latest updates</h2><p className="mt-1 text-sm text-white/85">Published case summaries · last {hours === 168 ? "7 days" : `${hours} hours`}</p></div><Button variant="outline" size="icon" className="relative rounded-full border-white/50 bg-white/90 text-forest hover:bg-white" aria-label="Refresh published updates" disabled={loaded.loading} onClick={loaded.retry}><RefreshCw size={17} aria-hidden="true" className={loaded.loading ? "motion-safe:animate-spin" : ""} /></Button></header>
      {loaded.failed && <p role="alert" className="mb-4 rounded-xl bg-amber-50 p-4 text-sm text-amber-950">{availability}</p>}
      {loaded.loading && !data && <FeedSkeleton />}
      {data && !items.length && <p className="px-2 py-14 text-center text-sm font-bold text-muted-foreground">No published updates match your filters.</p>}
      <div className="space-y-5">{items.slice(0, limit).map(item => <article key={item.id} className="overflow-hidden rounded-sm border border-primary/10 bg-white shadow-[0_18px_44px_-18px_#123c301a]">
        <header className="flex flex-wrap items-center gap-3 border-b border-primary/10 px-5 py-4"><ItemIcon item={item} /><div className="min-w-0 flex-1"><p className="text-sm font-extrabold">Published case update</p><time dateTime={item.time} className="mt-1 block text-xs text-muted-foreground">{formatTime(item.time)}</time></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${item.verification === "CONFIRMED_FIRE" ? "bg-orange-50 text-orange-900" : "bg-secondary text-primary"}`}>{item.verification && verificationLabels[item.verification]}</span></header>
        <div className="px-5 py-6 sm:px-7"><h3 className="text-2xl font-extrabold leading-snug tracking-tight">{item.title}</h3><dl className="mt-5 divide-y divide-primary/10 rounded-xl border border-primary/10 bg-secondary/25 px-4"><div className="py-4"><dt className="flex items-center gap-2 text-xs font-bold text-muted-foreground"><MapPin size={15} aria-hidden="true" />Published location</dt><dd className="mt-1.5 text-sm font-bold">{item.location}</dd></div><div className="py-4"><dt className="text-xs font-bold text-muted-foreground">Handling status</dt><dd className="mt-1.5 text-sm font-bold">{item.handling && handlingLabels[item.handling]}</dd></div></dl></div>
        <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-primary/10 px-5 py-3"><p className="max-w-xs text-xs leading-5 text-muted-foreground">Approved snapshot. Private reports and original evidence are not shared.</p><Button variant="ghost" className="rounded-full text-primary" onClick={event => select(item.id, event.currentTarget)}>View update<ArrowUpRight size={16} aria-hidden="true" /></Button></footer>
      </article>)}</div>
      {items.length > limit && <Button variant="outline" className="mt-5 w-full rounded-full" onClick={() => setLimit(value => value + 40)}>Show more</Button>}{data?.limited && <p className="mt-4 text-xs">Results are limited. Use a shorter time range.</p>}
    </div></section>}
    {!feed && <div className="absolute left-4 top-56 z-10 max-w-[calc(100%-96px)] rounded-2xl border border-white/80 bg-white/95 px-4 py-3 shadow-sm sm:left-6 sm:top-28 md:hidden"><p className="text-sm font-extrabold">Kalimantan</p><p role="status" className="mt-1 text-xs text-muted-foreground">{loaded.loading ? "Updating observations…" : data ? `${items.length} observations` : "Observations unavailable"}</p>{availability && <p className="mt-2 max-w-xs text-xs leading-5 text-amber-900">{availability}</p>}<button type="button" className="mt-1 min-h-11 text-xs font-extrabold text-primary underline underline-offset-4" data-worklist-trigger onClick={event => { setPanel("results"); openWorklist(event.currentTarget); }}>Open observation list</button></div>}
    <div inert={reportPending} className="absolute bottom-6 left-1/2 z-30 hidden w-[calc(100%-160px)] max-w-3xl -translate-x-1/2 items-center gap-1 rounded-full border border-primary/10 bg-white p-2 shadow-[0_8px_32px_-8px_#123c3040] sm:flex">{searchControl("observation-search")}{actions}</div>
    <Dialog.Root open={mobileOpen && (feed || !desktop)} onOpenChange={setMobileOpen}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-forest/30" /><Dialog.Content onCloseAutoFocus={event => { event.preventDefault(); restoreFocus(worklistOpener.current, '[data-worklist-trigger], [data-report-trigger]'); }} style={{ height: `${sheetHeight}dvh` }} className="fixed inset-x-0 bottom-0 z-60 flex max-h-[85dvh] flex-col overflow-hidden rounded-t-3xl border bg-white text-forest shadow-2xl md:inset-x-auto md:bottom-6 md:left-6 md:top-24 md:w-[380px] md:max-h-[calc(100vh-120px)] md:rounded-sm"><button type="button" className="min-h-11 shrink-0 touch-none border-b text-xs font-bold" aria-label="Resize sheet: drag or use up and down arrow keys" onPointerDown={event => start(event, "sheet")} onPointerMove={move} onPointerUp={pointerEnd} onPointerCancel={pointerEnd} onLostPointerCapture={pointerEnd} onKeyDown={event => { if (event.key === "ArrowUp" || event.key === "ArrowDown") { event.preventDefault(); setSheetHeight(value => Math.max(34, Math.min(86, value + (event.key === "ArrowUp" ? 5 : -5)))); } }}><span aria-hidden="true" className="mx-auto block h-1.5 w-12 rounded-full bg-primary/25" /><span className="sr-only">Resize panel</span></button><div className="flex shrink-0 items-center justify-between gap-3 border-b bg-secondary/40 px-5 py-3"><Dialog.Title className="text-lg font-extrabold">{selected ? "Observation details" : panel === "cases" ? "Coordination" : panel === "reports" ? "My reports" : "Observations"}</Dialog.Title><Dialog.Close asChild><Button size="icon" variant="ghost" aria-label="Close panel"><X size={18} aria-hidden="true" /></Button></Dialog.Close></div><Dialog.Description className="sr-only">{panel === "cases" ? "Authorized internal cases, separate from the public map." : "Published summaries and satellite observations. Not fire perimeters."}</Dialog.Description>
      <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain">{panelContent}</div></Dialog.Content></Dialog.Portal></Dialog.Root>
    {myReports && <section aria-label="My reports" style={desktop ? undefined : { height: `${reportsHeight}vh` }} className="absolute inset-x-0 bottom-0 z-40 flex h-[72vh] max-h-[82vh] flex-col overflow-hidden rounded-t-2xl border border-primary/10 bg-white shadow-xl md:inset-x-auto md:bottom-auto md:left-6 md:top-24 md:h-[calc(100vh-120px)] md:min-h-[min(400px,calc(100vh-120px))] md:max-h-[calc(100vh-120px)] md:w-[380px] md:min-w-[320px] md:max-w-[600px] md:resize md:rounded-sm"><button type="button" aria-label="Resize My reports with up or down arrow keys or drag" className="min-h-11 shrink-0 touch-none md:hidden" onPointerDown={event => start(event, "reports")} onPointerMove={move} onPointerUp={pointerEnd} onPointerCancel={pointerEnd} onLostPointerCapture={pointerEnd} onKeyDown={event => { if (event.key === "ArrowUp" || event.key === "ArrowDown") { event.preventDefault(); setReportsHeight(value => Math.max(44, Math.min(82, value + (event.key === "ArrowUp" ? 5 : -5)))); } }}><span aria-hidden="true" className="mx-auto block h-1.5 w-12 rounded-full bg-primary/25" /></button><header className="flex items-center justify-between border-b px-7 py-6"><h2 className="text-2xl font-extrabold">My reports</h2><Button asChild variant="ghost"><Link to={home} aria-label="Close My reports">Close</Link></Button></header><div className="min-h-0 flex-1 overflow-y-auto"><ReportsPage user={user} id={params.get("report")} onDraft={handleDetailDraft} /></div></section>}
    {pathname === home && <ReportPage detailDirty={detailDraft.dirty} detailPending={detailDraft.pending} onRestoreFocus={() => restoreFocus(reportOpener.current, '[data-report-trigger]')} desktop={desktop} style={desktop ? { left: reportBox.x, top: reportBox.y, width: reportBox.width, height: reportBox.height, bottom: "auto" } : { height: `${sheetHeight}vh` }} handle={<button type="button" aria-label={desktop ? "Move panel using arrow keys or drag" : "Resize panel using up and down arrow keys or drag"} className="min-h-11 shrink-0 touch-none border-b bg-secondary/40 text-xs font-bold" onPointerDown={event => start(event, desktop ? "move" : "sheet", true)} onPointerMove={move} onPointerUp={pointerEnd} onPointerCancel={pointerEnd} onLostPointerCapture={pointerEnd} onKeyDown={event => { if (desktop) keyboard(event, false, true); else if (event.key === "ArrowUp" || event.key === "ArrowDown") { event.preventDefault(); setSheetHeight(value => Math.max(34, Math.min(86, value + (event.key === "ArrowUp" ? 5 : -5)))); } }}><span aria-hidden="true" className="mx-auto block h-1.5 w-12 rounded-full bg-primary/25" /><span className="sr-only">{desktop ? "Move panel" : "Resize panel"}</span></button>} resizeHandle={desktop && <button type="button" aria-label="Resize panel using arrow keys or drag" className="min-h-11 shrink-0 touch-none border-t px-4 text-right text-xs font-bold" onPointerDown={event => start(event, "resize", true)} onPointerMove={move} onPointerUp={pointerEnd} onPointerCancel={pointerEnd} onLostPointerCapture={pointerEnd} onKeyDown={event => keyboard(event, true, true)}><span aria-hidden="true" className="mx-auto block h-1.5 w-12 rounded-full bg-primary/25" /><span className="sr-only">Resize panel</span></button>}
      open={reportOpen && !pick && !feed} onClose={closeReport} onPending={setReportPending} onPick={({ latitude, longitude, locationMode, receive }) => { if (reportPending) return; setPick({ latitude, longitude, locationMode, receive }); closeReport(); }} />}
    {pick && <section aria-labelledby="pick-title" className="absolute left-1/2 top-56 z-50 w-[calc(100%-32px)] max-w-md -translate-x-1/2 rounded-xl border border-primary/15 bg-white p-4 shadow-lg sm:top-28"><div className="flex items-start gap-3"><Crosshair className="mt-0.5 shrink-0 text-primary" size={20} aria-hidden="true" /><div><h2 id="pick-title" className="font-extrabold">Choose the {pick.locationMode === "OBSERVER_POSITION" ? "observer position" : "estimated incident location"}</h2><p role="status" className="mt-1 text-sm text-muted-foreground">Tap the map to place the pin, then drag it to adjust.</p></div></div>{pick.latitude && pick.longitude ? <p className="mt-3 rounded-lg bg-secondary/60 px-3 py-2 text-xs font-bold tabular-nums">Selected: {Number(pick.latitude).toFixed(6)}, {Number(pick.longitude).toFixed(6)}</p> : <p className="mt-3 text-xs font-bold text-amber-900">No location selected yet.</p>}<div className="mt-3 flex flex-wrap gap-2"><Button disabled={!pick.latitude || !pick.longitude} onClick={() => { pick.receive(pick.latitude, pick.longitude); setPick(null); openReport(); }}><Check size={16} aria-hidden="true" />Confirm location</Button><Button variant="outline" onClick={() => { setPick(null); openReport(); }}>Cancel</Button></div></section>}
  </main>;
}

function FeedSkeleton() {
  return <div role="status" aria-label="Loading published updates" className="space-y-5"><span className="sr-only">Loading published updates</span>{Array.from({ length: 3 }, (_, index) => <div key={index} className="animate-pulse overflow-hidden rounded-sm bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-primary/10 px-5 py-4"><span className="size-10 rounded-sm bg-secondary" /><span className="h-3 w-36 rounded-full bg-secondary" /></div><div className="space-y-4 px-5 py-6"><span className="block h-5 w-3/4 rounded-full bg-secondary" /><span className="block h-14 w-full rounded-sm bg-secondary/70" /></div></div>)}</div>;
}

function ItemIcon({ item }: { item: MapItem }) {
  const confirmed = item.kind === "publication" && item.verification === "CONFIRMED_FIRE";
  const Icon = item.kind === "hotspot" ? Satellite : confirmed ? Flame : ShieldCheck;
  return <span className={`grid size-10 shrink-0 place-items-center rounded-xl ${item.kind === "hotspot" ? "bg-amber-50 text-amber-800" : confirmed ? "bg-orange-50 text-orange-800" : "bg-secondary text-primary"}`}><Icon size={20} aria-hidden="true" /></span>;
}

function ItemDetail({ item }: { item: MapItem }) {
  return <section aria-label="Selected observation" className="p-5"><ItemIcon item={item} /><p className="mt-4 text-xs font-bold text-muted-foreground">{item.kind === "hotspot" ? "NASA FIRMS satellite observation" : "Privacy-reviewed published summary"}</p><h2 className="mt-2 text-xl font-extrabold">{item.title}</h2><p className="mt-4 rounded-xl bg-secondary/60 p-3 text-sm font-bold">{item.verification ? verificationLabels[item.verification] : "Hotspot — not a confirmed fire"}</p><dl className="mt-5 space-y-4 text-sm">{item.handling && <div><dt className="text-muted-foreground">Handling status</dt><dd>{handlingLabels[item.handling]}</dd></div>}<div><dt className="text-muted-foreground">Location</dt><dd>{item.location}{hasPoint(item) && <span className="block tabular-nums">{item.latitude.toFixed(5)}, {item.longitude.toFixed(5)}</span>}</dd></div><div><dt className="text-muted-foreground">{item.kind === "hotspot" ? "Detected" : "Published"}</dt><dd>{formatTime(item.time)}</dd></div>{item.kind === "hotspot" && <><div><dt className="text-muted-foreground">Satellite / instrument</dt><dd>{item.instrument || "Not supplied"}</dd></div><div><dt className="text-muted-foreground">Detection confidence</dt><dd>{item.confidence}</dd></div>{item.stale && <p className="text-amber-900">Updates delayed; this observation may be out of date.</p>}</>}</dl><p className="mt-5 border-t pt-4 text-xs leading-5 text-muted-foreground">{item.kind === "publication" ? "This is an approved snapshot, not a live private case. " : "Satellite detection is not human verification. "}</p></section>;
}

export function ErrorBoundary() {
  return <main className="grid min-h-dvh place-items-center bg-white p-6"><div className="max-w-md"><h1 className="text-2xl font-extrabold">Unable to open the dashboard</h1><p className="mt-3 text-muted-foreground">Your session could not be checked. No private dashboard data has been loaded.</p><div className="mt-5 flex flex-wrap gap-3"><Button onClick={() => window.location.reload()}>Retry</Button><Button asChild variant="outline"><Link to={dashboardLogin("USER")}>Member Login</Link></Button><Button asChild variant="outline"><Link to={dashboardLogin("ADMIN")}>Government Login</Link></Button></div></div></main>;
}
