import { useState } from "react";
import { Save, X } from "lucide-react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { submitGovernmentReportAction, updateGovernmentCase } from "@/api/dashboard/government";
import { updateMonitoringUser } from "@/api/dashboard/monitoring";
import { OperationsDialog, AssignmentAction, AssignmentForm, Freshness } from "./OperationsShared";
import { useQueryClient } from "@tanstack/react-query";
import { Button, FieldSelect } from "@/components/ui";
import { handlingLabels, priorityLabels, verificationLabels } from "@/constants";
import { useMonitoringAssignments, useMonitoringUser } from "@/hooks/dashboard";
import { useGovernmentCase, useGovernmentMutation, useGovernmentReport } from "@/hooks/dashboard/useGovernment";
import { observationAppearance, triageAppearance, triageMissing, triageReasons } from "@/lib/report-triage";
import { reportStatusLabel } from "@/lib/report-status";
import { formatTime } from "@/pages/dashboard/utils";
import ReportPhotos from "@/pages/reports/ReportPhotos";
import ReportTimeline from "@/pages/reports/ReportTimeline";
import type { MonitoringUser, Priority } from "@/types";
import type { CaseDetail, GovernmentReport } from "@/types/government";
import { ErrorPanel, panelClass, StatusPill } from "./MonitoringComponents";
import { useMonitoringContext } from "./MonitoringPage";
import { MonitoringDetailSkeleton } from "./MonitoringSkeletons";

const control = "mt-2 min-h-11 w-full rounded-lg border border-input bg-white px-3 text-sm";

function DetailDrawer({ title, closeTo, children }: { title: string; closeTo: string; children: React.ReactNode }) {
  const navigate = useNavigate();
  const { search } = useLocation();
  return <section aria-label={title} className="min-w-0 text-forest"><header className="flex min-h-16 items-center justify-between gap-4 rounded-xl border border-primary/10 bg-white px-4 shadow-[0_18px_50px_-42px_rgba(67,25,31,0.9)] sm:px-5"><div className="min-w-0"><p className="text-[10px] font-extrabold uppercase tracking-[0.14em] text-muted-foreground">Detail</p><h2 className="mt-1 truncate font-extrabold">{title}</h2></div><Button type="button" variant="ghost" size="icon" aria-label="Close detail" onClick={() => navigate(`${closeTo}${search}`, { replace: true })}><X size={20} aria-hidden="true" /></Button></header><div className="mt-5">{children}</div></section>;
}

function ReportContent({ user, report, refresh }: { user: ReturnType<typeof useMonitoringContext>["user"]; report: GovernmentReport; refresh: () => void }) {
  const { state } = useLocation();
  const initialStatus = report.reviewStatus === "DECLINED" ? "DECLINED" : report.reviewStatus === "REVIEWED" ? "REVIEWED" : "IN_PROGRESS";
  const [status, setStatus] = useState<"IN_PROGRESS" | "REVIEWED" | "DECLINED">(initialStatus);
  const [description, setDescription] = useState("");
  const mutation = useGovernmentMutation(user, async () => {
    await submitGovernmentReportAction(report.id, { status, description: description.trim(), attachmentIds: [], idempotencyKey: crypto.randomUUID() });
    setDescription("");
    refresh();
  });
  return <div className="space-y-5">
    <div className="space-y-5">
      <section className={`${panelClass} p-5 sm:p-6`}><div className="flex flex-wrap items-center gap-2"><StatusPill tone="info">{reportStatusLabel(report)}</StatusPill><StatusPill tone={report.triage.level === "CRITICAL" || report.triage.level === "HIGH" ? "warning" : "neutral"}>{triageAppearance[report.triage.level].label} priority</StatusPill></div><h2 className="mt-5 text-lg font-extrabold">What happened</h2><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{report.description}</p><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-xs font-bold text-muted-foreground">Reporter</dt><dd className="mt-1 font-bold">{report.reporter?.name ?? "Private reporter"}</dd><dd className="text-xs text-muted-foreground">{report.reporter?.email}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Observed</dt><dd className="mt-1 font-bold">{formatTime(report.observedAt)}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Location mode</dt><dd className="mt-1 font-bold">{report.locationMode === "OBSERVER_POSITION" ? "Observer position" : "Incident estimate"}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Location</dt><dd className="mt-1">{report.locationDescription || report.region?.name || "Not supplied"}</dd></div></dl><div className="mt-5 flex flex-wrap gap-3">{report.observationTypes.map(type => <span key={type} className="inline-flex items-center gap-2 rounded-full bg-secondary px-3 py-2 text-xs font-bold"><img src={`/icons8-${observationAppearance[type].icon}.png`} alt="" width={24} height={24} className="size-5" />{observationAppearance[type].label}</span>)}</div></section>
      <section className={`${panelClass} p-5 sm:p-6`}><h2 className="text-lg font-extrabold">Priority context</h2><p className="mt-3 text-sm leading-7">{triageReasons(report.triage)}</p><p className="mt-2 text-xs leading-6 text-muted-foreground">{triageMissing(report.triage)}</p></section>
      {report.attachments.length > 0 && <section className={`${panelClass} p-5 sm:p-6`}><h2 className="text-lg font-extrabold">Original photos</h2><ReportPhotos user={user} reportId={report.id} photos={report.attachments} /></section>}
      <section className={`${panelClass} p-5 sm:p-6`}><ReportTimeline report={report} user={user} /></section>
      {report.updates && report.updates.length > 0 && <section className={`${panelClass} p-5 sm:p-6`}><h2 className="text-lg font-extrabold">Updates</h2><ol className="mt-4 divide-y divide-primary/10">{report.updates.map(update => <li key={update.id} className="py-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs font-extrabold uppercase tracking-wide text-primary">{update.kind.toLowerCase()}</span><time className="text-xs text-muted-foreground">{formatTime(update.createdAt)}</time></div><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{update.message}</p></li>)}</ol></section>}
    </div>
    <OperationsDialog title={`Edit review: ${report.number}`} action="Edit" initialOpen={state?.edit === true} dirty={!!description || status !== initialStatus} pending={mutation.isPending} onClose={() => { setDescription(""); setStatus(initialStatus); mutation.reset(); }}><p className="mt-2 text-xs leading-6 text-muted-foreground">The original observation remains unchanged. This adds an audited progress entry.</p><form className="mt-5 space-y-4" onSubmit={event => { event.preventDefault(); mutation.mutate(); }}><fieldset disabled={mutation.isPending} className="space-y-4"><label htmlFor="monitoring-report-status" className="block text-sm font-bold">Status<FieldSelect disabled={mutation.isPending} id="monitoring-report-status" value={status} onValueChange={value => setStatus(value as typeof status)} options={[{ value: "IN_PROGRESS", label: "In progress" }, { value: "REVIEWED", label: "Reviewed" }, { value: "DECLINED", label: "Declined" }]} /></label><label className="block text-sm font-bold">Description<textarea required minLength={5} maxLength={2000} value={description} onChange={event => setDescription(event.target.value)} className={`${control} min-h-28 py-3`} /></label><Button className="w-full" disabled={description.trim().length < 5}><Save size={16} aria-hidden="true" />{mutation.isPending ? "Saving" : "Save review action"}</Button></fieldset>{mutation.error && <p role="alert" className="text-sm text-red-800">{mutation.error.message}</p>}{mutation.isSuccess && <p role="status" className="text-sm text-emerald-800">Review action saved.</p>}</form></OperationsDialog>
  </div>;
}

export function ReportDetailPage() {
  const { user } = useMonitoringContext();
  const { id = "" } = useParams();
  const resource = useGovernmentReport(user, id);
  return <DetailDrawer title={resource.data?.number ?? "Report detail"} closeTo="/monitoring/reports">{resource.failed && <ErrorPanel message="Report detail could not refresh." loading={resource.loading} retry={resource.retry} />}{resource.initialLoading && !resource.data && <MonitoringDetailSkeleton section="report" />}{resource.data && <ReportContent key={resource.data.id} user={user} report={resource.data} refresh={resource.retry} />}</DetailDrawer>;
}

function CaseContent({ user, detail, refresh, disabled }: { user: ReturnType<typeof useMonitoringContext>["user"]; detail: CaseDetail; refresh: () => void; disabled: boolean }) {
  const assignments = useMonitoringAssignments(user);
  const client = useQueryClient();
  const refreshAssignments = async () => { await client.invalidateQueries({ queryKey: ["dashboard", user.id, user.role] }); };
  const mutation = useGovernmentMutation(user, async (priority: Priority) => {
    await updateGovernmentCase(detail.id, { version: detail.version, priority, reason: "Manual priority override from monitoring dashboard" });
    refresh();
  });
  return <div className="space-y-5">
    <section className={`${panelClass} p-5 sm:p-6`}><header className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-extrabold">Assignments</h2>{assignments.data && <OperationsDialog title={`Create assignment: ${detail.number}`} action="Create" disabled={disabled || assignments.failed || assignments.loading || detail.handling === "CLOSED" || detail.verification === "NOT_FIRE"}><AssignmentForm user={user} detail={detail} operations={assignments.data} refresh={refreshAssignments} disabled={disabled || assignments.failed || assignments.loading} /></OperationsDialog>}</header>{assignments.failed && <ErrorPanel message="Assignments could not refresh." loading={assignments.loading} retry={assignments.retry} />}{assignments.initialLoading && <p role="status" className="mt-4 text-sm">Loading assignments…</p>}{assignments.data && <ul className="mt-4 divide-y divide-primary/10">{assignments.data.assignments.filter(item => item.caseId === detail.id).map(item => <li key={item.id} className="flex flex-wrap items-start justify-between gap-4 py-4"><div><p className="font-bold">{item.teamName}</p><StatusPill>{item.status.toLowerCase().replaceAll("_", " ")}</StatusPill><p className="my-2 text-sm">{item.notes || "No task description recorded"}</p><Freshness observedAt={null} updatedAt={item.updatedAt} /></div><OperationsDialog title={`Edit assignment: ${item.teamName}`} action="Edit" disabled={disabled || assignments.failed || assignments.loading}><AssignmentAction user={user} item={item} refresh={refreshAssignments} /></OperationsDialog></li>)}</ul>}{assignments.data && !assignments.data.assignments.some(item => item.caseId === detail.id) && <p className="mt-4 text-sm text-muted-foreground">No teams assigned to this case.</p>}</section>
    <div className="space-y-5"><section className={`${panelClass} p-5 sm:p-6`}><div className="flex flex-wrap gap-2"><StatusPill tone={detail.verification === "CONFIRMED_FIRE" ? "danger" : detail.verification === "NOT_FIRE" ? "success" : "warning"}>{verificationLabels[detail.verification]}</StatusPill><StatusPill tone="info">{handlingLabels[detail.handling]}</StatusPill><StatusPill>{priorityLabels[detail.priority]}</StatusPill></div><h2 className="mt-5 text-xl font-extrabold">{detail.title}</h2><dl className="mt-6 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-xs font-bold text-muted-foreground">Version</dt><dd className="mt-1 font-bold">{detail.version}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Opened</dt><dd className="mt-1 font-bold">{formatTime(detail.openedAt)}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Region</dt><dd className="mt-1">{detail.region?.name || "Not mapped"}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Internal location</dt><dd className="mt-1">{detail.latitude === null ? "Not recorded" : `${detail.latitude}, ${detail.longitude}`}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Mapped perimeter</dt><dd className="mt-1">{detail.areaHectares === null ? "Not available" : `${detail.areaHectares.toLocaleString("en", { maximumFractionDigits: 2 })} ha approximate`}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Active assignments</dt><dd className="mt-1 font-bold">{detail.activeAssignmentCount}</dd></div></dl></section><section className={`${panelClass} p-5 sm:p-6`}><h2 className="text-lg font-extrabold">Field evidence</h2>{detail.fieldUpdates.length === 0 ? <p className="mt-3 text-sm text-muted-foreground">No field evidence recorded.</p> : <ol className="mt-4 divide-y divide-primary/10">{detail.fieldUpdates.map(update => <li key={update.id} className="py-4"><div className="flex flex-wrap justify-between gap-2"><span className="font-extrabold">{update.findings.toLowerCase().replaceAll("_", " ")}</span><span className="text-xs text-muted-foreground">{formatTime(update.observedAt)}</span></div><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{update.description}</p><p className="mt-1 text-xs text-muted-foreground">{update.source}</p></li>)}</ol>}</section>{detail.analysisLimitations.length > 0 && <section className={`${panelClass} p-5 sm:p-6`}><h2 className="text-lg font-extrabold">Analysis limitations</h2>{detail.analysisLimitations.map((analysis, index) => <div key={index} className="mt-4"><p className="text-xs font-bold text-muted-foreground">{analysis.current ? "Current analysis" : "Historical analysis"} · {formatTime(analysis.completedAt)}</p><ul className="mt-2 list-disc space-y-2 pl-5 text-sm">{analysis.limitations.map(item => <li key={item}>{item}</li>)}</ul></div>)}</section>}</div>
    <aside className={`${panelClass} p-5 sm:p-6`}><h2 className="text-lg font-extrabold">Manual priority override</h2><p className="mt-2 text-xs leading-6 text-muted-foreground">Choose a new priority when the current assessment appears incorrect. The change saves immediately and is added to history.</p><label htmlFor="monitoring-case-priority" className="mt-5 block text-sm font-bold">Priority<FieldSelect id="monitoring-case-priority" value={detail.priority} disabled={mutation.isPending} onValueChange={value => { const next = value as Priority; if (next !== detail.priority) mutation.mutate(next); }} options={Object.entries(priorityLabels).map(([value, label]) => ({ value, label }))} /></label>{mutation.isPending && <p role="status" className="mt-3 text-sm text-muted-foreground">Saving priority change…</p>}{mutation.error && <p role="alert" className="mt-3 text-sm text-red-800">{mutation.error.message}</p>}{mutation.isSuccess && <p role="status" className="mt-3 text-sm text-emerald-800">Priority updated and added to history.</p>}<section className="mt-7 border-t border-primary/10 pt-5"><h3 className="font-extrabold">Priority history</h3>{detail.priorityHistory.length === 0 ? <p className="mt-3 text-sm text-muted-foreground">No manual priority changes recorded.</p> : <ol className="mt-3 divide-y divide-primary/10">{detail.priorityHistory.map(entry => <li key={entry.id} className="py-4"><div className="flex flex-wrap items-center gap-2 text-sm"><StatusPill>{priorityLabels[entry.from]}</StatusPill><span aria-hidden="true">→</span><StatusPill tone={entry.to === "HIGH" ? "danger" : entry.to === "MEDIUM" ? "warning" : "neutral"}>{priorityLabels[entry.to]}</StatusPill></div><p className="mt-2 text-xs text-muted-foreground">{entry.changedBy} · {formatTime(entry.changedAt)}</p></li>)}</ol>}</section></aside>
  </div>;
}

export function CaseDetailPage() {
  const { user } = useMonitoringContext();
  const { id = "" } = useParams();
  const resource = useGovernmentCase(user, id);
  return <DetailDrawer title={resource.data?.number ?? "Case detail"} closeTo="/monitoring/cases">{resource.failed && <ErrorPanel message="Case detail could not refresh." loading={resource.loading} retry={resource.retry} />}{resource.initialLoading && !resource.data && <MonitoringDetailSkeleton section="case" />}{resource.data && <CaseContent key={resource.data.id} user={user} detail={resource.data} refresh={resource.retry} disabled={resource.failed || resource.loading} />}</DetailDrawer>;
}

function UserContent({ actor, item, refresh }: { actor: ReturnType<typeof useMonitoringContext>["user"]; item: MonitoringUser; refresh: () => void }) {
  const { state } = useLocation();
  const [name, setName] = useState(item.name);
  const [role, setRole] = useState<MonitoringUser["role"]>(item.role);
  const [active, setActive] = useState(item.active);
  const [reason, setReason] = useState("");
  const [mandate, setMandate] = useState("");
  const mutation = useGovernmentMutation(actor, async () => {
    await updateMonitoringUser(item.id, { expectedUpdatedAt: item.updatedAt, ...(name.trim() !== item.name ? { name: name.trim() } : {}), ...(role !== item.role ? { role } : {}), ...(active !== item.active ? { active } : {}), reason: reason.trim(), ...((role !== item.role || active !== item.active) ? { mandate: mandate.trim() } : {}) });
    setReason(""); setMandate(""); refresh();
  });
  const authorityChanged = role !== item.role || active !== item.active;
  const dirty = name.trim() !== item.name || authorityChanged || !!reason || !!mandate;
  return <div className="mt-7 space-y-5">
    <section className={`${panelClass} p-5 sm:p-6`}><div className="flex flex-wrap gap-2"><StatusPill tone={item.role === "ADMIN" ? "info" : "neutral"}>{item.role}</StatusPill><StatusPill tone={item.active ? "success" : "danger"}>{item.active ? "Active" : "Inactive"}</StatusPill><StatusPill tone={item.emailVerified ? "success" : "warning"}>{item.emailVerified ? "Verified email" : "Unverified email"}</StatusPill></div><dl className="mt-7 grid gap-5 text-sm sm:grid-cols-2"><div><dt className="text-xs font-bold text-muted-foreground">Name</dt><dd className="mt-1 font-extrabold">{item.name}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Email</dt><dd className="mt-1 break-all font-bold">{item.email}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Created</dt><dd className="mt-1">{formatTime(item.createdAt)}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Last updated</dt><dd className="mt-1">{formatTime(item.updatedAt)}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Incident confirmation</dt><dd className="mt-1">{item.canConfirmIncidents ? "Allowed by effective ADMIN role" : "Not allowed"}</dd></div><div><dt className="text-xs font-bold text-muted-foreground">Information publishing</dt><dd className="mt-1">{item.canPublishInformation ? "Allowed by effective ADMIN role" : "Not allowed"}</dd></div></dl></section>
    <OperationsDialog title={`Edit user: ${item.name}`} action="Edit" initialOpen={state?.edit === true} dirty={dirty} pending={mutation.isPending} onClose={() => { setName(item.name); setRole(item.role); setActive(item.active); setReason(""); setMandate(""); mutation.reset(); }}><p className="mt-2 text-xs leading-6 text-muted-foreground">Email and verification are read-only. Role or active-state changes revoke current sessions.</p><form className="mt-5 space-y-4" onSubmit={event => { event.preventDefault(); mutation.mutate(); }}><fieldset disabled={mutation.isPending} className="space-y-4"><label className="block text-sm font-bold">Name<input required minLength={1} maxLength={200} value={name} onChange={event => setName(event.target.value)} className={control} /></label><label htmlFor="monitoring-user-role" className="block text-sm font-bold">Role<FieldSelect disabled={mutation.isPending} id="monitoring-user-role" value={role} onValueChange={value => setRole(value as MonitoringUser["role"])} options={[{ value: "USER", label: "User" }, { value: "ADMIN", label: "Administrator" }]} /></label><label className="flex min-h-11 items-center gap-3 rounded-lg border border-input px-3 text-sm font-bold"><input type="checkbox" checked={active} onChange={event => setActive(event.target.checked)} />Active account</label><label className="block text-sm font-bold">Reason<textarea required minLength={5} maxLength={2000} value={reason} onChange={event => setReason(event.target.value)} className={`${control} min-h-24 py-3`} /></label>{authorityChanged && <label className="block text-sm font-bold">Authority mandate<input required minLength={3} maxLength={500} value={mandate} onChange={event => setMandate(event.target.value)} className={control} /></label>}<Button className="w-full" disabled={!dirty || name.trim().length < 1 || reason.trim().length < 5 || authorityChanged && mandate.trim().length < 3}><Save size={16} aria-hidden="true" />{mutation.isPending ? "Saving" : "Save user changes"}</Button></fieldset>{mutation.error && <p role="alert" className="text-sm text-red-800">{mutation.error.message}</p>}{mutation.isSuccess && <p role="status" className="text-sm text-emerald-800">User updated. Authority changes revoked existing sessions.</p>}</form></OperationsDialog>
  </div>;
}

export function UserDetailPage() {
  const { user } = useMonitoringContext();
  const { id = "" } = useParams();
  const resource = useMonitoringUser(user, id);
  return <DetailDrawer title={resource.data?.name ?? "User detail"} closeTo="/monitoring/users">{resource.failed && <ErrorPanel message="User detail could not refresh." loading={resource.loading} retry={resource.retry} />}{resource.initialLoading && !resource.data && <MonitoringDetailSkeleton section="user" />}{resource.data && <UserContent key={resource.data.id} actor={user} item={resource.data} refresh={resource.retry} />}</DetailDrawer>;
}
