import { ListChecks } from "lucide-react";
import type { DashboardUser, OwnReport } from "@/types";
import ReportPhotos from "./ReportPhotos";

const labels: Record<string, string> = { NEW: "Received", UNDER_REVIEW: "In progress", NEEDS_DETAILS: "In progress — more details requested", REVIEWED: "Reviewed", DECLINED: "Declined — report disposition, not a fire finding", CONFIRMED_FIRE: "Confirmed", NOT_FIRE: "Verified not fire — inspection finding", INCONCLUSIVE: "Verification inconclusive", CORRECTION_CONFIRMED_FIRE: "Decision corrected: fire confirmed", CORRECTION_NOT_FIRE: "Decision corrected: not fire", OPEN: "Case reopened", CHECK_SCHEDULED: "Check scheduled", ON_SCENE: "On scene", RESPONDING: "Responding", MONITORING: "Monitoring", CLOSED: "Closed" };
export default function ReportTimeline({ report, user }: { report: OwnReport; user: DashboardUser }) {
  const events = [{ id: `received-${report.id}`, stage: "NEW", description: "", createdAt: report.createdAt, actorDisplay: "Report received", attachments: [] }, ...(report.progress ?? [])].sort((a, b) => Date.parse(a.createdAt) - Date.parse(b.createdAt));
  return <section aria-label="Report progress" className="mt-6"><h3 className="flex items-center gap-2 font-extrabold"><ListChecks size={19} className="text-primary" aria-hidden="true" />Progress</h3><ol className="mt-3 ml-2 border-l border-primary/20">{events.map(event => <li key={event.id} className="relative pb-5 pl-5"><span aria-hidden="true" className="absolute -left-1.5 top-1 size-3 rounded-full border-2 border-white bg-primary" /><h4 className="text-sm font-bold">{labels[event.stage] ?? event.stage.toLowerCase().replaceAll("_", " ")}</h4>{event.description && <p className="mt-1 whitespace-pre-wrap text-sm leading-6">{event.description}</p>}{!!event.attachments?.length && <section aria-label="Progress evidence photos"><h5 className="mt-2 text-xs font-bold">Evidence photos</h5><ReportPhotos user={user} reportId={report.id} photos={event.attachments} /></section>}<p className="mt-1 text-xs text-muted-foreground">{event.actorDisplay} · <time dateTime={event.createdAt}>{new Date(event.createdAt).toLocaleString("en-GB", { timeZone: "UTC" })} UTC</time></p></li>)}</ol>{!report.progress?.length && <p className="text-xs text-muted-foreground">No progress descriptions have been recorded.</p>}</section>;
}
