export type ObservationType = "SMOKE" | "FLAME" | "BURNING_SMELL";
export type ReportDraft = {
  observationTypes: ObservationType[];
  observedLocal: string;
  timeChoice: "" | "NOW" | "EARLIER";
  locationMode: "INCIDENT_ESTIMATE" | "OBSERVER_POSITION";
  latitude: string;
  longitude: string;
  confirmed: boolean;
  accuracyMeters: number | null;
  description: string;
};
export type ReportPayload = {
  observationTypes: ObservationType[];
  observedAt: string;
  locationMode: ReportDraft["locationMode"];
  latitude: number | null;
  longitude: number | null;
  accuracyMeters: number | null;
  regionId: string | null;
  locationDescription: string;
  description: string;
  attachmentIds: string[];
  idempotencyKey: string;
};
export type Region = { id: string; name: string; timezone: string; code: string; level: number };
export type OwnReport = {
  id: string; number: string; observationTypes: ObservationType[]; observedAt: string; createdAt: string;
  locationMode: ReportDraft["locationMode"]; latitude: number | null; longitude: number | null;
  accuracyMeters: number | null; locationDescription: string; description: string;
  reviewStatus: "NEW" | "UNDER_REVIEW" | "NEEDS_DETAILS" | "REVIEWED" | "DECLINED";
  progress?: { id: string; stage: string; description: string; createdAt: string; actorDisplay: string; attachments?: { id: string; filename: string; contentType: string; size: number }[] }[];
  region: { id: string; name: string; timezone: string } | null;
  case: { number: string; title?: string; verificationStatus: string; handlingStatus: string; perimeter?: import("@/lib/perimeter").PublicPerimeter | null } | null;
  windContext?: import("@/lib/wind").WindContext | null;
  attachments: { id: string; filename: string; size: number; contentType: string }[];
  coverAttachment?: { id: string; filename: string } | null;
  updates?: { id: string; message: string; kind: string; authorRole: string; createdAt: string; attachments: { id: string; filename: string; contentType: string; size: number }[] }[];
};
export type ReportList = { data: OwnReport[]; meta: { total: number; page: number; pageSize: number } };
export type ReportPhoto = { file: File; preview: string; id?: string; intentId?: string; uploaded?: boolean; progress: number; error?: string };
