import { Select } from "radix-ui";
import { Check, ChevronDown } from "lucide-react";

export function FieldSelect({ id, value, onValueChange, options, placeholder, disabled = false, required = false, invalid = false, describedBy }: { id: string; value: string; onValueChange: (value: string) => void; options: { value: string; label: string; disabled?: boolean }[]; placeholder?: string; disabled?: boolean; required?: boolean; invalid?: boolean; describedBy?: string }) {
  const choices = placeholder ? [{ value: "__empty", label: placeholder }, ...options] : options;
  return <Select.Root value={value || "__empty"} onValueChange={value => onValueChange(value === "__empty" ? "" : value)} disabled={disabled} required={required}>
    <Select.Trigger id={id} aria-required={required} aria-invalid={invalid} aria-describedby={describedBy} className="mt-2 flex min-h-11 w-full items-center justify-between gap-3 rounded-lg border border-primary/25 bg-white px-3 py-2 text-left text-sm font-normal focus-visible:outline-2 focus-visible:outline-primary disabled:opacity-60"><Select.Value /><Select.Icon><ChevronDown size={16} aria-hidden="true" /></Select.Icon></Select.Trigger>
    <Select.Portal><Select.Content position="popper" sideOffset={6} collisionPadding={12} className="z-[100] max-h-[var(--radix-select-content-available-height)] w-[var(--radix-select-trigger-width)] overflow-y-auto rounded-lg border border-primary/20 bg-white p-1 text-forest shadow-xl"><Select.Viewport>{choices.map(option => <Select.Item key={option.value} value={option.value} disabled={option.disabled} className="data-[disabled]:pointer-events-none data-[disabled]:opacity-50 flex min-h-11 cursor-pointer items-center justify-between gap-3 rounded-md px-3 py-2 text-sm outline-none data-[highlighted]:bg-emerald-50 data-[state=checked]:bg-primary data-[state=checked]:text-white"><Select.ItemText>{option.label}</Select.ItemText><Select.ItemIndicator><Check size={16} aria-hidden="true" /></Select.ItemIndicator></Select.Item>)}</Select.Viewport></Select.Content></Select.Portal>
  </Select.Root>;
}
